version: 0.2
phases:
  install: 
    runtime-versions:
      php: 7.3 
  pre_build: # commands to be run before build
    commands:
    - echo AWS Version
    - aws --version

    - echo Backup old Project build
    - mkdir -p $EFSPATH/backup # Create 'backup' folder for Project if doesn't exist
    - rsync -aq --delete-after --exclude 'backup/' --exclude 'php-fpm/' --exclude 'nginx/' --exclude 'logs/' $EFSPATH/ $EFSPATH/backup/ # Sync current project into 'backup'

    - echo Sync without deleting extraneous destination files
    - rsync -aq --exclude 'backup/' . $EFSPATH/ # Copy new without updating - Important to do this first and separetely for fresh installation and to prevent removing system generated files

    - echo Use backup - forward all requests to backup if available
    - echo `date` >> $EFSPATH/backup/.active
    
    - echo Sync and delete extraneous destination files
    - rsync -aq --delete-after --exclude 'backup/' --exclude 'vendor/' --exclude 'storage/' --exclude 'public/' --exclude 'php-fpm/' --exclude 'nginx/' --exclude 'logs/' . $EFSPATH/
    
    - echo Update Permissions
    - chmod -R -f 777 $EFSPATH/app $EFSPATH/public $EFSPATH/storage 
  build:
    commands:
    - echo Build started on `date`

    - echo Installing composer..
    - cd $EFSPATH && composer install

    - echo Creating and updating .env file..
    - cd $EFSPATH && cp $ENVFILE .env

    - cd $EFSPATH && php artisan env:set AWS_ACCESS_KEY_ID=$AWSAccessKey -q
    - cd $EFSPATH && php artisan env:set AWS_SECRET_ACCESS_KEY=$AWSAccessSecret -q
    - cd $EFSPATH && php artisan env:set AWS_DEFAULT_REGION=$AWS_REGION -q

    - echo Generate Laravel APP Key
    - cd $EFSPATH && php artisan key:generate -q

    - echo Create Laravel Passport Keys if not available
    - cd $EFSPATH && php artisan passport:keys -q

    - echo Clear Cache
    - cd $EFSPATH && php artisan route:clear -q
    - cd $EFSPATH && php artisan config:clear -q
    - cd $EFSPATH && php artisan cache:clear -q

    - echo Generate secure configs
    - cd $EFSPATH && php artisan config:secure -q

    - echo Restart Queue to pick up on changes
    - cd $EFSPATH && php artisan queue:restart -q

  post_build:
    commands: 
    - echo Stop using backup
    - rm -f $EFSPATH/backup/.active

    - echo Build completed on `date`

cache:
  paths:
    - 'vendor/**/*'