AWSTemplateFormatVersion: '2010-09-09'
Description: 'Continuous Delivery for Laravel Project using S3 as source and EFS as destination.'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stacks'
      Parameters:
      - ParentVPCStack 
      - ParentClusterStack 
      - ParentClusterServiceStack 
      - ParentAlertStack
    - Label:
        default: 'CodeBuild Parameters'
      Parameters:
      - CodeBuildDesc
      - CacheBucketName
      - AZA
      - AZB
      - SubnetsReach
      - AWSAccessKey
      - AWSAccessSecret 
      - AWSRegion
      - ENVFILE 
    - Label:
        default: 'CodePipeline Parameters'
      Parameters:
      - ArtifactBucketName
      - SourceBucketName
      - SourceBucketKey
    - Label:
        default: 'Global Tags'
      Parameters:
      - ENV
      - SYS
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc.yaml template.'
    Type: String
  ParentClusterStack:
    Description: 'Stack name of parent Cluster stack based on ecs.yaml template.'
    Type: String
  ParentClusterServiceStack:
    Description: 'Stack name of parent Cluster service stack based on ecs-service-laradock.yaml template.'
    Type: String
  ParentAlertStack:
    Description: 'Optional but recommended stack name of parent alert stack based on alert.yaml template.'
    Type: String
    Default: ''

  CodeBuildDesc:
    Description: 'Description of the CodeBuild Project'
    Type: String 
    Default: 'Build Project to build Laravel project from S3 unto EFS File System'
  CacheBucketName:
    Description: 'Name of S3 Bucket to use to cache Codebuild dependencies. Ignore if you prefer not to cache'
    Type: String 
    Default: ''
  AZA:
    Description: 'Use Availability Zone A (Choose at least one AZ)'
    Type: String
    Default: true
    AllowedValues:
    - true
    - false
  AZB:
    Description: 'Use Availability Zone B (Choose at least one AZ)'
    Type: String
    Default: true
    AllowedValues:
    - true
    - false
  SubnetsReach:
    Description: 'Should the code build container have direct access to the Internet or do you prefer private subnets with NAT?'
    Type: String
    Default: Private
    AllowedValues:
    - Public
    - Private 
  ENVFILE:
    Description: 'Environment file to use when setting up Laravel Project. This env file will be copied into ".env" file. Use ".env.dev" for Development, ".env.prod" for Production'
    Type: String 
    Default: '.env.dev'
    AllowedValues:
    - '.env.dev'
    - '.env.prod'
  AWSAccessKey:
    Description: 'AWS Secret Manager reference for AWS Access Key for APP - with sufficient permissions like AWS Secret Manager, S3 etc. Format = secret-id:json-key:version-stage:version-id '
    Type: String 
  AWSAccessSecret:
    Description: 'AWS Secret Manager reference for AWS Access Secret APP - with sufficient permissions like AWS Secret Manager, S3 etc. Format = secret-id:json-key:version-stage:version-id '
    Type: String 
  AWSRegion:
    Description: 'Default AWS Region for APP'
    Type: String 
    Default: 'ap-southeast-1' 

  ArtifactBucketName:
    Description: 'Name of S3 Bucket to use to store Pipeline Artifacts'
    Type: String 
  SourceBucketName:
    Description: 'Name of S3 Bucket that holds the Source Codes. Note: This bucket must support Versioning'
    Type: String 
  SourceBucketKey:
    Description: 'Object name or path in S3 Bucket that holds Source Codes. Do not include (/) infront. e.g dev/Sample.zip or Sample.zip'
    Type: String 

  ENV:
    Description: 'Specify Environment to deploy Resource (dev,staging,prod)'
    Type: String
    Default: 'dev'
    AllowedValues:
    - 'dev'
    - 'staging'
    - 'prod'
  SYS:
    Description: 'Specify type System the resource is associated with this Resource (backend,frontend,both)'
    Type: String
    AllowedValues:
    - 'backend'
    - 'frontend'
    - 'both'
  
Conditions:
  HasCacheBucketName: !Not [!Equals [!Ref CacheBucketName, '']]
  HasAZA: !Equals [!Ref AZA, 'true']
  HasAZB: !Equals [!Ref AZB, 'true']
  HasAlertTopic: !Not [!Equals [!Ref ParentAlertStack, '']]

Resources:

  # Codebuild Role
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 's3:*'
                - 'secretsmanager:*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                Effect: Allow
                Resource: '*'

  # Codebuild Project
  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Ref 'AWS::StackName'
      Description: !Ref CodeBuildDesc
      Source:
        Type: 'CODEPIPELINE'
        BuildSpec: !Sub | 
          version: 0.2
          phases:
            install: 
              runtime-versions:
                php: 7.3 
            pre_build: # commands to be run before build
              commands:
              - echo AWS Version
              - aws --version

              - echo Backup old Project build
              - mkdir -p $EFSPATH/backup # Create 'backup' folder for Project if doesn't exist
              - rsync -aq --delete-after --exclude 'backup/' --exclude 'php-fpm/' --exclude 'nginx/' --exclude 'logs/' $EFSPATH/ $EFSPATH/backup/ # Sync current project into 'backup'

              - echo Sync without deleting extraneous destination files
              - rsync -aq --exclude 'backup/' . $EFSPATH/ # Copy new without updating - Important to do this first and separetely for fresh installation and to prevent removing system generated files

              - echo Use backup - forward all requests to backup if available
              - echo `date` >> $EFSPATH/backup/.active
              
              - echo Sync and delete extraneous destination files
              - rsync -aq --delete-after --exclude 'backup/' --exclude 'vendor/' --exclude 'storage/' --exclude 'public/' --exclude 'php-fpm/' --exclude 'nginx/' --exclude 'logs/' . $EFSPATH/
              
              - echo Update Permissions
              - chmod -R -f 777 $EFSPATH/app $EFSPATH/public $EFSPATH/storage 
            build:
              commands:
              - echo Build started on `date`

              - echo Installing composer..
              - cd $EFSPATH && composer install

              - echo Creating and updating .env file..
              - cd $EFSPATH && cp $ENVFILE .env

              - cd $EFSPATH && php artisan env:set AWS_ACCESS_KEY_ID=$AWSAccessKey -q
              - cd $EFSPATH && php artisan env:set AWS_SECRET_ACCESS_KEY=$AWSAccessSecret -q
              - cd $EFSPATH && php artisan env:set AWS_DEFAULT_REGION=$AWSRegion -q

              - echo Generate Laravel APP Key
              - cd $EFSPATH && php artisan key:generate -q

              - echo Create Laravel Passport Keys if not available
              - cd $EFSPATH && php artisan passport:keys -q

              - echo Clear Cache
              - cd $EFSPATH && php artisan route:clear -q
              - cd $EFSPATH && php artisan config:clear -q
              - cd $EFSPATH && php artisan cache:clear -q

              - echo Generate secure configs
              - cd $EFSPATH && php artisan config:secure -q

              - echo Restart Queue to pick up on changes
              - cd $EFSPATH && php artisan queue:restart -q

            post_build:
              commands: 
              - echo Stop using backup
              - rm -f $EFSPATH/backup/.active

              - echo Build completed on `date`
        InsecureSsl: false
      SecondarySources: []
      SecondarySourceVersions: []
      Artifacts:
        Type: CODEPIPELINE
      SecondaryArtifacts: []
      Cache:
        Type: !If [HasCacheBucketName, 'S3', 'NO_CACHE']
        Location: !If [HasCacheBucketName, !Sub '${CacheBucketName}/${AWS::StackName}', !Ref 'AWS::NoValue']
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:4.0
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
        - Name: EFSPATH
          Value: "/mnt/efs"
          Type: PLAINTEXT
        - Name: ENVFILE
          Value: !Ref ENVFILE
          Type: PLAINTEXT
        - Name: AWSAccessKey
          Value: !Ref AWSAccessKey
          Type: SECRETS_MANAGER
        - Name: AWSAccessSecret
          Value: !Ref AWSAccessSecret
          Type: SECRETS_MANAGER
        - Name: AWSRegion
          Value: !Ref AWSRegion
          Type: PLAINTEXT
        PrivilegedMode: true
        ImagePullCredentialsType: CODEBUILD
      ServiceRole: !Ref CodeBuildRole
      TimeoutInMinutes: 30
      QueuedTimeoutInMinutes: 480
      Tags:
      - Key: ENV
        Value: !Ref ENV
      - Key: SYS
        Value: !Ref SYS
      VpcConfig:
        VpcId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}
        Subnets:
        - !If [HasAZA, {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetA${SubnetsReach}'}, !Ref 'AWS::NoValue']
        - !If [HasAZB, {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetB${SubnetsReach}'}, !Ref 'AWS::NoValue']
        SecurityGroupIds:
        - {'Fn::ImportValue': !Sub '${ParentVPCStack}-SecurityGroup'}
      BadgeEnabled: false
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: aws-codebuild
          StreamName: !Sub '${AWS::StackName}'
        S3Logs:
          Status: DISABLED
          EncryptionDisabled: false
      FileSystemLocations:
      - Type: EFS
        Location: !Sub
          - '${EFSId}.efs.${Region}.amazonaws.com:/${StackName}'
          - EFSId: {'Fn::ImportValue': !Sub '${ParentClusterStack}-EFS'}
            Region: !Sub '${AWS::Region}'
            StackName: {'Fn::ImportValue': !Sub '${ParentClusterServiceStack}-StackName'}
        MountPoint: "/mnt/efs"
        Identifier: 'APP_EFS'
        MountOptions: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2


  # CodePipeline Role
  CodePipelineRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [codepipeline.amazonaws.com]
          Version: '2012-10-17'
        Path: /
        Policies:
          - PolicyName: CodePipelineAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Action:
                  - 'logs:*'
                  - 's3:*'
                  - 'events:*'
                  - 'codestar:*'
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                  Resource: "*"
                  Effect: Allow

  # CodePipeline              
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref 'AWS::StackName'
      RoleArn: !GetAtt 'CodePipelineRole.Arn'
      ArtifactStore:
        Type: S3
        Location: !Sub '${ArtifactBucketName}'
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          ActionTypeId:
            Category: Source
            Owner: AWS
            Provider: S3
            Version: '1'
          RunOrder: 1
          Configuration:
            PollForSourceChanges: true
            S3Bucket: !Ref SourceBucketName
            S3ObjectKey: !Ref SourceBucketKey
          OutputArtifacts:
          - Name: SourceArtifact
          InputArtifacts: []
          Region: ap-southeast-1
          Namespace: SourceVariables
      - Name: Build
        Actions:
        - Name: Build
          ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          RunOrder: 1
          Configuration:
            ProjectName: !Ref   CodeBuildProject
          OutputArtifacts:
          - Name: BuildArtifact
          InputArtifacts:
          - Name: SourceArtifact
          Region: !Ref 'AWS::Region'
          Namespace: BuildVariables
  
  # Code Pipeline Notification Rule
  CodepipelinedNotificationRule:
    Type: 'AWS::CodeStarNotifications::NotificationRule'
    Condition: HasAlertTopic
    Properties:
      Name: !Sub ${CodePipeline}-Notification-Rule
      DetailType: FULL
      Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}"
      EventTypeIds: 
      - codepipeline-pipeline-stage-execution-failed
      - codepipeline-pipeline-pipeline-execution-succeeded
      Targets: 
      - TargetType: SNS 
        TargetAddress: {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
  

Outputs:
  TemplateID:
    Description: 'AWS Cloud Formation template id'
    Value: 'ecs-efs-deploy'
  TemplateVersion:
    Description: 'AWS Cloud Formation template version.'
    Value: '1.0'
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
    Export:
      Name: !Sub '${AWS::StackName}-StackName'

  CodeBuildProject:
    Description: 'Name of CodeBuild Project'
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub '${AWS::StackName}-CodeBuildProject'
  CodeBuildProjectArn:
    Description: 'ARN for CodeBuild Project'
    Value: !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${CodeBuildProject}"
    Export:
      Name: !Sub '${AWS::StackName}-CodeBuildProjectArn'

  CodePipeline:
    Description: 'Name of CodePipeline'
    Value: !Ref CodePipeline
    Export:
      Name: !Sub '${AWS::StackName}-CodePipeline'
  CodePipelineArn:
    Description: 'ARN for CodePipeline'
    Value: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}"
    Export:
      Name: !Sub '${AWS::StackName}-CodePipelineArn'